name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: alvinalfandy
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          branch: main
          message: 'Update contribution snake'